#!/bin/bash

# This script prompts me to do the items of a daily '.routine' file and keeps track of what I report doing.

FILE="${1}"
routine="${FILE%.routine}"

cat "$FILE" | while read code name
do
	while true
	do
		echo " == $name == " | tr a-z A-Z
		echo "Press enter when you start, 'skip' to skip this, or 'already' to indicate it is already done."
		read skip < /dev/tty
		if [ "x$skip" = "xskip" ]
		then
			echo "SKIPPED !"
		elif [ "x$skip" = "xalready" ]
		then
			echo "Already completed."
			echo $code, $routine, , $(date -Is -d @$stop), "$name", "finished earlier" >> routinedata.csv
		elif [ "x$skip" = "x" ]
		then
			start=$(date +%s)
			echo
			echo " $name ... "
			echo
			while true
			do
				echo "Press enter when completed, or 'abort' to give up."
				read abort < /dev/tty
				if [ "x$abort" = "xabort" ]
				then
					echo ' ABORTED !'
					echo $code, $routine, $(date -Is -d @$start), $(date -Is -d @$stop), "$name", UNFINISHED >> routinedata.csv
				elif [ "x$abort" = "x" ]
				then
					stop=$(date +%s)
			
					echo $code, $routine, $(date -Is -d @$start), $(date -Is -d @$stop), "$name", >> routinedata.csv
				else
					echo "I couldn't recognize '$abort' ... try again?"
					continue
	
				fi
				break
			done
		else
			echo "I couldn't recognize '$skip' ... try again?"
			continue
		fi
		break
	done
	git add routinedata.csv
	git commit -m "$(date -I) $routine $name"
	torify git pull
	torify git push >/dev/null 2>&1 &
done
